import "./globals.css";
import type { Metadata } from "next";
import ThemeRegister from "@/app/components/ThemeRegister";
import React from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<ThemeRegister>{children}</ThemeRegister>
			</body>
		</html>
	);
}
